Feat BEIN-13411 Implement the new use case class
beincom/dto pull request #21
Opened 2023-05-23 07:37 UTC by quochung-bic

2023-05-23 09:05 UTC, quochung-bic commented on src/activity-log/enums/activity-log-use-case.enum.ts
> +export enum ACTIVITY_LOG_USE_CASES {
A implement theo những cái đang có á Trang

2023-05-24 02:19 UTC, khanhhuyen-bic requested changes
em tính sơ sơ đâu đó sẽ có khoảng 40 usecase nếu để flat hết ra trong folder `use-cases` thì sẽ rất dài và sau cũng khó tìm, nên em nghĩ là gom nhóm lại thành các folder bên trong sẽ tốt hơn

2023-05-24 02:19 UTC, khanhhuyen-bic commented on src/activity-log/enums/activity-log-use-case.enum.ts
> +  UPDATE_GROUP_PROFILE = 'update.group.profile',
sao mình không đặt giá trị theo tầng từ scope đi xuống, ví dụ như 
```
ASSIGN_COMMUNITY_ADMIN = 'community.admin.assign',
REVOKE_COMMUNITY_ADMIN =  'community.admin.revoke',
ADD_GROUP_MEMBER = 'group.member.add',
JOIN_GROUP_AS_MEMBER = 'group.member.join',
JOIN_GROUP_AS_ADMIN = 'group.admin.join'
```
với lại grooming hôm trước thì scope là community thì phần member chỉ có assign với revoke admin là riêng thôi còn lại các usecase khác quy hết về root group nên em nghĩ sẽ không còn `ADD_MEMBER_TO_COMMUNITY`

2023-05-24 02:19 UTC, khanhhuyen-bic commented on src/user-id.value-object.ts
>  export class UserId extends UUID {
UserId này có phải là UserId đã thêm vào dto chung không vậy ạ?

2023-05-24 02:21 UTC, khanhhuyen-bic commented on src/activity-log/dtos/activity-log-common.dto.ts
> +  requestId?: string;
`requestId` ở đây anh thêm vào là để xem các log sinh ra từ 1 hành động gốc là cái nào đúng không ạ? Nhưng nếu lưu như này thì em chưa biết sẽ truy ra kiểu gì?

2023-05-24 03:17 UTC, quochung-bic commented on src/activity-log/dtos/activity-log-common.dto.ts
> +  requestId?: string;
Trong mỗi record/document, thì mình sẽ lưu thêm request id này, để khi cần thì mình query (theo request id được cung cấp, hoặc là lấy request id dựa theo 1 record nào đó mà mình muốn trace)

2023-05-25 03:11 UTC, quochung-bic commented on src/activity-log/enums/activity-log-use-case.enum.ts
> +  UPDATE_GROUP_PROFILE = 'update.group.profile',
Về scope: như hôm qua trao đổi với @khanhhuyen-bic thì value này đã có sẵn, và đã lưu vào các records trong DB, nên tạm thời sẽ giữ nguyên nhé. 
Về use-case 'ADD_MEMBER_TO_COMMUNITY', thì hiện tại a thấy mình vẫn còn event này á em, nên sẽ đánh giá sau nhé @khanhhuyen-bic

2023-05-25 04:55 UTC, khanhhuyen-bic approved these changes

2023-05-26 02:59 UTC, merged