BEIN-15193 dto for move group log
beincom/dto pull request #34
Opened 2023-06-01 10:32 UTC by diemtrang-bic

2023-06-01 11:58 UTC, minhdat-bic requested changes
conflict + wrong version

2023-06-02 04:20 UTC, minhdat-bic approved these changes

2023-06-02 04:24 UTC, quochung-bic commented on src/activity-log/use-cases/badge/group-badge.use-case.ts
> +      badge: objectData.badges[objectId],
Ủa @diemtrang-bic ơi, vậy badge lúc log thì nó bị đè luôn!

2023-06-02 04:26 UTC, quochung-bic commented on src/activity-log/use-cases/group/move-group.use-case.ts
> +        community,
Mình có cần lưu community ko nhỉ?

2023-06-02 04:27 UTC, diemtrang-bic commented on src/activity-log/use-cases/group/move-group.use-case.ts
> +        community,
Em tính lưu phòng hờ, mà chắc cũng không cần nên để em remove luôn.

2023-06-02 04:46 UTC, diemtrang-bic commented on src/activity-log/use-cases/badge/group-badge.use-case.ts
> +      badge: objectData.badges[objectId],
Data lúc log thì có field object á anh. Field badge này để hover vô hiển thị data hiện tại.

2023-06-02 04:48 UTC, quochung-bic commented on src/activity-log/use-cases/group/move-group.use-case.ts
> +      communityId: community.id,
E lấy communityId từ group luôn, để mình bỏ biến community á

2023-06-02 04:49 UTC, quochung-bic commented on src/activity-log/use-cases/group/move-group.use-case.ts
> +        group,
Chỗ này có bị thừa ko e nhỉ?

2023-06-02 06:55 UTC, quochung-bic commented on src/activity-log/use-cases/group/move-group.use-case.ts
> +type PayloadDTO = Omit<BasePayloadDTO<MovedGroup>, 'community'>;
A recommend là dùng Pick, thay vì Omit, vì cái BasePayloadDTO or BaseDataDTO thì sau này vẫn có thể cập nhật thêm cái khác á

2023-06-02 06:55 UTC, quochung-bic approved these changes

2023-06-02 07:09 UTC, merged