feat(patch): BEIN-16062 update group setting use case
beincom/dto pull request #46
Opened 2023-06-23 08:06 UTC by diemtrang-bic

2023-06-23 08:10 UTC, khanhhuyen-bic requested changes

2023-06-23 08:10 UTC, khanhhuyen-bic commented on src/activity-log/use-cases/group/update-group-profile.use-case.ts
> +  changes: ActivityPropChangedDTO<GroupProfileState>;
em nghĩ payload thì mình không cho truyền settings, còn data do có dữ liệu cũ nên mình mới thêm settings vào

2023-06-23 08:37 UTC, quochung-bic commented on src/activity-log/use-cases/group/update-group-profile.use-case.ts
> +        object: data.currentState,
Cái này có thừa ko e nhỉ? Mình đã có group rồi á.

2023-06-23 08:39 UTC, diemtrang-bic commented on src/activity-log/use-cases/group/update-group-profile.use-case.ts
> +        object: data.currentState,
Hôm qua Huyền nói để object cho nó đồng bộ luôn nên em để vô chứ thừa thật.

2023-06-23 08:42 UTC, quochung-bic commented on src/activity-log/use-cases/group/update-group-profile.use-case.ts
> +        object: data.currentState,
Mình có 2 dữ liệu:
+ Lúc log
+ Hiện tại (cần bind) -> Chỉ khai báo ở DataDTO, chứ ko cần lưu á

2023-06-23 09:10 UTC, diemtrang-bic commented on src/activity-log/use-cases/group/update-group-profile.use-case.ts
> +        object: data.currentState,
À cái object này em tính lưu object setting thôi, vì cái `group` chỉ chứa có mấy field của ActivityLogGroupDTO.

2023-06-23 09:29 UTC, quochung-bic commented on src/activity-log/use-cases/group/update-group-profile.use-case.ts
> +      group: data.group,
Chỗ này thì vẫn cần fallback từ cái snapshot cho những log cũ á e

2023-06-23 09:33 UTC, diemtrang-bic commented on src/activity-log/use-cases/group/update-group-profile.use-case.ts
> +      group: data.group,
ủa khi nào thì khô truyền group vậy anh, field đó required mà.

2023-06-23 09:35 UTC, quochung-bic commented on src/activity-log/use-cases/group/update-group-profile.use-case.ts
> +      group: data.group,
Log phiên bản tiên khởi, thì chỉ có snapshot, ko có group á e :D. Sau này làm lại mới, thì a bổ sung thêm group. Nên những log cũ sẽ ko có group, và mình sẽ lấy từ snapshot bind vào á.

2023-06-23 09:36 UTC, diemtrang-bic commented on src/activity-log/use-cases/group/update-group-profile.use-case.ts
> +      group: data.group,
:oizoioi:

2023-06-23 09:42 UTC, quochung-bic approved these changes

2023-06-23 10:47 UTC, khanhhuyen-bic approved these changes

2023-06-26 04:07 UTC, minhdat-bic approved these changes

2023-06-26 04:07 UTC, merged